### PR TITLE
Add support for s8s8 dynamic quant

### PR DESCRIPTION
**Pull request by jondea**
This will be used in PyTorch for accelerating dynamic quantization by using s8s8 matmul accelerated by ACL (see
https://github.com/oneapi-src/oneDNN/pull/1885). This can go in without oneDNN 3.5, but will only offer performance benefits after it does.

Also, do you have a policy on copyright headers? I noticed that on this branch at least, most of the copyright headers were removed a few years ago. However, Arm's usual policy when contributing to open source projects is to include a copyright header on any file which is modified. Would this be acceptable? If not, is there somewhere else suitable to note copyright?

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
The change LGTM. I'm not sure about the copyright though. cc @jingxu10 and @Guobing-Chen

**Comment by jondea** [comment]
Thanks @jgong5. Given that this file doesn't have an existing copyright notice, would it be acceptable to add an Arm copyright line in the top level header file? This seems to be one of the only references to copyright on the pytorch_ideep branch https://github.com/intel/ideep/blob/a9e5602a1a5c93e270479e88b38c81e223b19fa9/include/ideep.hpp#L2

**Comment by jondea** [comment]
I'm happy to get this in without the copyright notices, and work it out later. What's the process for getting this merged?

**Comment by yanbing-j** [comment]
Do you include this change in PyTorch CI? If so, I can merge directly.
cc @Xia-Weiwen to review more.

**Comment by Xia-Weiwen** [comment]
> Do you include this change in PyTorch CI? If so, I can merge directly. cc @Xia-Weiwen to review more.

LGTM

**Pull request merged**
