### PR TITLE
Remove conv weight scale reciprocal

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
After oneDNN 3.1 upgrade, we don't need do the weight scale reciprocal calculation. So, remove the duplicated reciprocal calculation to optimize QConv performance.

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
Hi @jgong5 @Xia-Weiwen, could you help to take a look of this PR?

**Review by jgong5 — APPROVED** [review]
LGTM. This depends on onednn 3.x right, otherwise would result in incorrectness, right?

**Comment by leslie-fang-intel** [comment]
> LGTM. This depends on onednn 3.x right, otherwise would result in incorrectness, right?

Yes, we need to merge PR: https://github.com/pytorch/pytorch/pull/105996 firstly before update PyTorch IDeep to this commit.

**Comment by leslie-fang-intel** [comment]
Hi @yanbing-j, could you help to merge it?

**Pull request merged**
