### PR TITLE
matmul: add dynamic quantization for 2-in-1 compute scenario

### PR DESCRIPTION
**Pull request by snadampal**
matmul compute: 2-in-1 is missing the support for dynamic quantization. This PR adds the missing logic.

### CODE REVIEW

**Comment by snadampal** [comment]
cc: @XiaobingSuper @yanbing-j , appreciate if you or someone from your side can review this.

**Comment by snadampal** [comment]
appreciate if someone can review this PR.

**Comment by yanbing-j** [comment]
@jgong5 @Xia-Weiwen can help review.

**Review by jgong5 — APPROVED** [review]

**Comment by snadampal** [comment]
thank you!

**Comment by Xia-Weiwen** [comment]
Hi @snadampal Though the PR is merged, I would still like to know if you have run any tests with this patch, e.g., PyTorch UTs?

**Comment by snadampal** [comment]
Hi @Xia-Weiwen , no I didn't run PyTorch UTs, I tested few use cases with real models. If you could share the list of UT I need to check on x86, happy to do that.

**Comment by Xia-Weiwen** [comment]
> Hi @Xia-Weiwen , no I didn't run PyTorch UTs, I tested few use cases with real models. If you could share the list of UT I need to check on x86, happy to do that.

@snadampal, I see. We will include this in PyTorch 2.2 soon and run PyTorch's CI.

**Pull request merged**
