### PR TITLE
fix convolution compute_binary build issue

### PR DESCRIPTION
**Pull request by XiaobingSuper**
This PR is about fix the **compute_binary** API build issue that calling a wrong **do_prepare** API, and also removing the INT8 path which we don't enable it now.

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
@jgong5 @Guobing-Chen

**Comment by Guobing-Chen** [comment]
Add Weiwen for INT8. @Xia-Weiwen

**Comment by Xia-Weiwen** [comment]
Please do not remove the int8 path. I think we will use it for conv-add-relu fusion for int8 in stock pytorch in the future.

**Comment by XiaobingSuper** [comment]
I think we can first remove the INT8 path, because it has not been tested, we can't make sure it works.

**Comment by Xia-Weiwen** [comment]
> I think we can first remove the INT8 path, because it has not been tested, we can't make sure it works.

OK

**Review by jgong5 — APPROVED** [review]

**Pull request merged**
